### ISSUE TITLE
[Tech]: Release

### ISSUE THREAD

**Issue by N1ghtStorm** [sora-xor/sora2-parachain#105]
# Task List

## Before the Release
- Global
  - [x] sora-xor/sora2-parachain#151
- Mainnet
  - [x] sora-xor/sora2-parachain#152
  - [x] sora-xor/sora2-parachain#153
  - [x] sora-xor/sora2-parachain#154
- Parachain
  - [ ] #155
  - [x] sora-xor/sora2-parachain#156
  - [x] sora-xor/sora2-parachain#157

## After the Release
- Mainnet
  - [x] sora-xor/sora2-parachain#158
  - [x] sora-xor/sora2-network#792
- Parachain
  - [x] sora-xor/sora2-parachain#160
  - [x] sora-xor/sora2-parachain#161
  - [x] sora-xor/sora2-parachain#162
  - [x] sora-xor/sora2-parachain#163

**Comment by Tieumsan** [comment]
@bgodlin provide instructions here

**Comment by stefashkaa** [comment]
I just put it here...
Polkaswap requires:
- KSM icon
- XCM fee
